version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - store_test_results:
          path: .coverage
      - run:
          name: Publish
          command: scripts/ci-publish-release.sh
